server:
  port: 8764
spring:
  application:
     name: info
  profiles:
      active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        file-extension: yml
      config:
        server-addr: localhost:8848
rabbitMq:
    host: 120.46.192.17
    portStr: 5672
    user: root
    password: 13772445559ldnnm~

