server:
  port: 8764
spring:
  application:
     name: info
  profiles:
      active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        file-extension: yml
      config:
        server-addr: localhost:8848


