server:
  port: 8763
spring:
  application:
     name: info
  profiles:
      active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        file-extension: yml
      config:
        server-addr:  localhost:8848
huawei:
    endpoint: https://obs.cn-north-4.myhuaweicloud.com
    url: testliudong.obs.cn-north-4.myhuaweicloud.com
    accessKeyId: NULOVK6JBE1HY1YCPJ4V
    accessKey: J6HqulLKHVvJ1rgVfjSrZEufb62h2PnTNxRDg8Uq
    obsBucketName: testliudong
