server:
  port: 8763
spring:
  application:
     name: info
  profiles:
      active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        file-extension: yml
      config:
        server-addr:  localhost:8848
huawei:
    endpoint: obs.cn-north-4.myhuaweicloud.com
    url: testliudong.obs.cn-north-4.myhuaweicloud.com
    accessKeyId: RBBKS2CXGLPBDL0PCC3Na
    accessKey: Nv2xaHKmC8KsBEQG5bpuZxlv0VDHhKkNPo2fk52O
    obsBucketName: testliudong
