server:
  port: 8763
spring:
  application:
     name: info
  profiles:
      active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        file-extension: yml
      config:
        server-addr: localhost:8848
huawei:
    endpoint: obs.cn-north-4.myhuaweicloud.com
    endpointOcr: ocr.cn-north-4.myhuaweicloud.com
    accessKeyId: MPVALJB9IUUS0DFBXX77
    accessKey: H6BOhSGTqU4iDdqpWRqCiAjS9UYnhWdKCFsvcqDc
    projectId: cf0a68733cc544be8530656fafe84c1c
rabbitMq:
    host: 120.46.192.17
    portStr: 5672
    user: root
    password: 13772445559ldnnm~

