
spring:
  application:
     name: info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userinfos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
      ## Redis数据库索引（默认为0）
      database: 0
      ## Redis服务器连接端口
      port: 6379
      ## Redis服务器地址
      host: 127.0.0.1
      ## Redis服务器连接密码（默认为空）
      password:
      jedis:
        pool:
          ## 连接池最大连接数（使用负值表示没有限制）
          #spring.redis.pool.max-active=8
          max-active: 8
          ## 连接池最大阻塞等待时间（使用负值表示没有限制）
          #spring.redis.pool.max-wait=-1
          max-wait: -1
          ## 连接池中的最大空闲连接
          #spring.redis.pool.max-idle=8
          max-idle: 8
          ## 连接池中的最小空闲连接
          #spring.redis.pool.min-idle=0
          min-idle: 0
      ## 连接超时时间（毫秒）
      timeout: 1200
      cache:
        redis:
          time-to-live: 1800s
        cache-names: menus_cache
        type: redis

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

