spring:
  cloud:
    nacos:
      discovery:
        server-addr:  localhost:8848
        file-extension: yml
      config:
        server-addr:  localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

